#ifndef UTILS_HPP
#define UTILS_HPP

#include <new>
#include <numeric>

template <typename T, std::size_t Alignment>
struct AlignedAllocator {
    using value_type = T;
        
    static_assert(Alignment >= alignof(T), "Alignment must be at least alignof(T)");
    static_assert((Alignment & (Alignment - 1)) == 0, "Alignment must be a power of two");

    AlignedAllocator() noexcept = default;
    template <typename U> AlignedAllocator(const AlignedAllocator<U, Alignment>&) noexcept {}

    template <typename U>
    struct rebind {
        using other = AlignedAllocator<U, Alignment>;
    };

    T *allocate(std::size_t n) {
        if (n == 0) return nullptr;
        if (n > std::numeric_limits<std::size_t>::max()/sizeof(T)) throw std::bad_alloc();
        std::size_t size = n * sizeof(T);
        void *ptr = ::operator new(size, std::align_val_t(Alignment));
        return static_cast<T*>(ptr);
    }

    void deallocate(T *p, std::size_t) noexcept {
        ::operator delete(p, std::align_val_t(Alignment));
    }

    // equality operator required by allocator traits, operator != automatically generated by C++20
    template <typename U>
    friend bool operator==(const AlignedAllocator&, const AlignedAllocator<U, Alignment>&) noexcept { return true; }
};

float randd(float l, float r);

float sigmoid(float x);

#endif